### ISSUE TITLE
Parse body when exception is returned

### ISSUE THREAD

**Issue by PVince81** [owncloud/davclient.js#11]
Currently we only get the body as string.

Would be nice to have it automatically parsed (or have a helper method) to make it possible to get the actual error message.

**Comment by evert** [comment]
I think it's a good idea, but I don't 100% know how to make this work for every system. The message sabre/dav embeds is non-standard. At the very least we can provide a parser for these xml bodies so people have the option to parse it.

**Comment by PVince81** [comment]
I was thinking of adding a utility method `parseSabreException(body)` but then it makes this lib depend/advertise Sabre.

**Comment by evert** [comment]
Some of the xml response is actually standard. Forget how much though. Probably not the human-readable error messsage, which might be what you want =)

**Comment by evert** [comment]
Looks like it's just the root element:

https://tools.ietf.org/html/rfc4918#section-14.5

However, some error responses do have standard elements in them, such as "supported-lock". But I don't know exactly how we could map this to something that is very useful yet. I think it's interesting though.

**Comment by evert** [comment]
Perhaps we could add a map of 'elements to look for' and map them to specific exceptions. For instance, we could map "supported-lock" a specific LockTypeNotSupported exception, and so forth. But your use-case was the human-readable message.

For that I don't particularly mind depending on something sabre/dav specific, but then perhaps we should formalize the element better, perhaps as some sort of "spec" type thing like:

http://sabre.io/dav/http-patch/

At the very least we give people a sane way to interop with this.

**Comment by PVince81** [comment]
Talked to @noveens, he'll take care of this.

**Comment by PVince81** [comment]
Closing this, in ownCloud we're now simply parsing the exception on the consumer side.
