### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/davclient.js#22]
@evert after https://github.com/evert/davclient.js/pull/21 is merged, would be good to tag a release as v0.1 or so.

We are now using bower to pull dependencies in owncloud core and it's better to point to an actual tag than a commit id: https://github.com/owncloud/core/blob/master/bower.json#L31

**Comment by PVince81** [comment]
Let me know if you agree with this and I'll push a v0.1 tag

**Comment by evert** [comment]
Yep totally!

**Comment by evert** [comment]
Make the tag `0.0.1` to be consistent with semver

**Comment by PVince81** [comment]
https://github.com/evert/davclient.js/tree/0.0.1
