### ISSUE TITLE
package.json not matching tag version

### ISSUE THREAD

**Issue by PVince81** [owncloud/davclient.js#28]
@evert bower complains that the tag 0.1.0 doesn't match package.json which you forgot to update.

If you have no objection I'm going to make a 0.1.1 tag with the matching package.json update.
(unless you want to reposition the tag, but usually that's not good practice)

**Comment by evert** [comment]
Sounds good to me!

**Comment by PVince81** [comment]
Here we go https://github.com/evert/davclient.js/commit/1122c53e6e7e9d8a104870171f54a9c7cb091fdd.
Tagged as 0.1.1.
