### ISSUE TITLE
Project take over

### ISSUE THREAD

**Issue by evert** [owncloud/davclient.js#29]
Hi @PVince81 ,

I thought I would contact you through a github issue. You are the number 1 contributer to this project, doubling my own contributions.

How would you feel about officially taking over this project? I don't think I will take it anywhere, any time soon. Even if you don't spend a lot of time on this, I feel this project is in better hands with you instead of me. How would you feel about this? If you are interested, let me know how you want to deal with this repo.

I can transfer ownership to your account, I can add it to the fruux org, I can keep it under my account or place it anywhere else you'd like.

Lemme know!

Evert

**Comment by PVince81** [comment]
Since this lib is mostly used and improved in the context of ownCloud I'd suggest moving it to the owncloud organization in which I'll continue maintaining it.

@hodyroff @deepdiver1975 what do you think ?

**Comment by evert** [comment]
Works for me! Let me know when/if you are certain. If so, I will initiate the transfer

**Comment by DeepDiver1975** [comment]
> If so, I will initiate the transfer

just for the process: please transfer the repo to me - me being an admin of the owncloud orga I can move it further. THX

**Comment by evert** [comment]
Just sent the request!

**Comment by DeepDiver1975** [comment]
:fearful: I was toooo slow in accepting the request ..... I'm sorry - can you please send it again? THX

**Comment by evert** [comment]
Ehh. It's already on owncloud ?

**Comment by DeepDiver1975** [comment]
Sorry.  It was late.... thanks a lot
