### ISSUE TITLE
parseUrl fails on url having underscore

### ISSUE THREAD

**Issue by chriseqipe** [owncloud/davclient.js#32]
### Steps to reproduce
1. create an owncloud instance accepting a domain with _ (for example test_123.thismycooldomain.org
2. Install calendar app
3. try to create new calendar --> Uncaught (in promise) TypeError: Cannot read property '0' of null in Chrome debugger console

var parts = url.match(/^(?:([A-Za-z]+):)?(\/{0,3})([0-9.\-A-Za-z]+)(?::(\d+))?(?:\/([^?#]*))?(?:\?([^#]*))?(?:#(.*))?$/); 

should be 

var parts = url.match(/^(?:([A-Za-z]+):)?(\/{0,3})([0-9.\-A-Za-z_]+)(?::(\d+))?(?:\/([^?#]*))?(?:\?([^#]*))?(?:#(.*))?$/);

**Comment by evert** [comment]
Underscores are not valid in domain names.
