### ISSUE TITLE
jQuery 3 Upgrade

### ISSUE THREAD

**Issue by lordelix** [owncloud/davclient.js#37]
# jQuery 3 Upgrade

See the full [upgrade 3.0 guide](https://jquery.com/upgrade-guide/3.0/)

## Deferred

`.then()`

- [ ] /lib/client.js

## Event

`.bind()`

- [ ] /lib/client.js
- [ ] /tests/client.test.js

**Comment by PVince81** [comment]
are we even using jquery here ??

**Comment by lordelix** [comment]
Looking into it, we don't … but my standard scan for js methods does not reveal this. So I guess we can close this already.
